(cl:in-package neuroadaptive_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          KAPPA-VAL
          KAPPA
          KV-VAL
          KV
          LAMBDA-VAL
          LAMBDA
          KZ-VAL
          KZ
          ZB-VAL
          ZB
          F-VAL
          F
          G-VAL
          G
          INPARAMS-VAL
          INPARAMS
          OUTPARAMS-VAL
          OUTPARAMS
          HIDDENNODES-VAL
          HIDDENNODES
          ERRORPARAMS-VAL
          ERRORPARAMS
          FEEDFORWARDFORCE-VAL
          FEEDFORWARDFORCE
          NN_ON-VAL
          NN_ON
          CARTPOS_KP_X-VAL
          CARTPOS_KP_X
          CARTPOS_KP_Y-VAL
          CARTPOS_KP_Y
          CARTPOS_KP_Z-VAL
          CARTPOS_KP_Z
          CARTPOS_KD_X-VAL
          CARTPOS_KD_X
          CARTPOS_KD_Y-VAL
          CARTPOS_KD_Y
          CARTPOS_KD_Z-VAL
          CARTPOS_KD_Z
          CARTROT_KP_X-VAL
          CARTROT_KP_X
          CARTROT_KP_Y-VAL
          CARTROT_KP_Y
          CARTROT_KP_Z-VAL
          CARTROT_KP_Z
          CARTROT_KD_X-VAL
          CARTROT_KD_X
          CARTROT_KD_Y-VAL
          CARTROT_KD_Y
          CARTROT_KD_Z-VAL
          CARTROT_KD_Z
          USECURRENTCARTPOSE-VAL
          USECURRENTCARTPOSE
          USENULLSPACEPOSE-VAL
          USENULLSPACEPOSE
          CARTINIX-VAL
          CARTINIX
          CARTINIY-VAL
          CARTINIY
          CARTINIZ-VAL
          CARTINIZ
          CARTINIROLL-VAL
          CARTINIROLL
          CARTINIPITCH-VAL
          CARTINIPITCH
          CARTINIYAW-VAL
          CARTINIYAW
          CARTDESX-VAL
          CARTDESX
          CARTDESY-VAL
          CARTDESY
          CARTDESZ-VAL
          CARTDESZ
          CARTDESROLL-VAL
          CARTDESROLL
          CARTDESPITCH-VAL
          CARTDESPITCH
          CARTDESYAW-VAL
          CARTDESYAW
          M-VAL
          M
          D-VAL
          D
          K-VAL
          K
          TASK_MA-VAL
          TASK_MA
          TASK_MB-VAL
          TASK_MB
))