# Velocity controller
float64 restPGain_
float64 restDGain_
float64 velPGain_
float64 velDGain_

float64 rThresh_
float64 psiThresh_

#Torque controller
float64 rotPGain_
float64 rotDGain_

# Impedance controller
float64 Kp_vel_x_
float64 Kp_vel_y_
float64 Kp_vel_z_
float64 Kd_vel_x_
float64 Kd_vel_y_
float64 Kd_vel_z_
float64 Kp_rot_x_
float64 Kp_rot_y_
float64 Kp_rot_z_
float64 Kd_rot_x_
float64 Kd_rot_y_
float64 Kd_rot_z_