(cl:defpackage neuroadaptive_msgs-srv
  (:use )
  (:export
   "CONTROLLERPARAMUPDATE"
   "<CONTROLLERPARAMUPDATE-REQUEST>"
   "CONTROLLERPARAMUPDATE-REQUEST"
   "<CONTROLLERPARAMUPDATE-RESPONSE>"
   "CONTROLLERPARAMUPDATE-RESPONSE"
   "SETCARTPOSE"
   "<SETCARTPOSE-REQUEST>"
   "SETCARTPOSE-REQUEST"
   "<SETCARTPOSE-RESPONSE>"
   "SETCARTPOSE-RESPONSE"
   "FIXEDWEIGHTTOGGLE"
   "<FIXEDWEIGHTTOGGLE-REQUEST>"
   "FIXEDWEIGHTTOGGLE-REQUEST"
   "<FIXEDWEIGHTTOGGLE-RESPONSE>"
   "FIXEDWEIGHTTOGGLE-RESPONSE"
   "SAVECONTROLLERDATA"
   "<SAVECONTROLLERDATA-REQUEST>"
   "SAVECONTROLLERDATA-REQUEST"
   "<SAVECONTROLLERDATA-RESPONSE>"
   "SAVECONTROLLERDATA-RESPONSE"
  ))

